const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD'

const GET_ROBOTS_PENDING = 'GET_ROBOTS_PENDING'
const GET_ROBOTS_SUCCESS = 'GET_ROBOTS_SUCCESS'
const GET_ROBOTS_FAILED = 'GET_ROBOTS_FAILED'

export {
  SET_SEARCH_FIELD,
  GET_ROBOTS_PENDING,
  GET_ROBOTS_SUCCESS,
  GET_ROBOTS_FAILED,
}
